name: cloudimage_360_view
description: A simple, interactive resource that can be used to provide a virtual tour of your product.
version: 1.0.0
homepage: https://github.com/abdelrahmanmostafa21/flutter-cloudimage-360-view

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: